/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MingshuRouteImport } from './routes/mingshu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MingshuIndexRouteImport } from './routes/mingshu/index'
import { Route as MingshuYungeRouteImport } from './routes/mingshu/yunge'
import { Route as MingshuKefuRouteImport } from './routes/mingshu/kefu'
import { Route as MingshuBaziRouteImport } from './routes/mingshu/bazi'
import { Route as MingshuBaogeRouteImport } from './routes/mingshu/baoge'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MingshuRoute = MingshuRouteImport.update({
  id: '/mingshu',
  path: '/mingshu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MingshuIndexRoute = MingshuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MingshuRoute,
} as any)
const MingshuYungeRoute = MingshuYungeRouteImport.update({
  id: '/yunge',
  path: '/yunge',
  getParentRoute: () => MingshuRoute,
} as any)
const MingshuKefuRoute = MingshuKefuRouteImport.update({
  id: '/kefu',
  path: '/kefu',
  getParentRoute: () => MingshuRoute,
} as any)
const MingshuBaziRoute = MingshuBaziRouteImport.update({
  id: '/bazi',
  path: '/bazi',
  getParentRoute: () => MingshuRoute,
} as any)
const MingshuBaogeRoute = MingshuBaogeRouteImport.update({
  id: '/baoge',
  path: '/baoge',
  getParentRoute: () => MingshuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mingshu': typeof MingshuRouteWithChildren
  '/register': typeof RegisterRoute
  '/mingshu/baoge': typeof MingshuBaogeRoute
  '/mingshu/bazi': typeof MingshuBaziRoute
  '/mingshu/kefu': typeof MingshuKefuRoute
  '/mingshu/yunge': typeof MingshuYungeRoute
  '/mingshu/': typeof MingshuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/mingshu/baoge': typeof MingshuBaogeRoute
  '/mingshu/bazi': typeof MingshuBaziRoute
  '/mingshu/kefu': typeof MingshuKefuRoute
  '/mingshu/yunge': typeof MingshuYungeRoute
  '/mingshu': typeof MingshuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mingshu': typeof MingshuRouteWithChildren
  '/register': typeof RegisterRoute
  '/mingshu/baoge': typeof MingshuBaogeRoute
  '/mingshu/bazi': typeof MingshuBaziRoute
  '/mingshu/kefu': typeof MingshuKefuRoute
  '/mingshu/yunge': typeof MingshuYungeRoute
  '/mingshu/': typeof MingshuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mingshu'
    | '/register'
    | '/mingshu/baoge'
    | '/mingshu/bazi'
    | '/mingshu/kefu'
    | '/mingshu/yunge'
    | '/mingshu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/mingshu/baoge'
    | '/mingshu/bazi'
    | '/mingshu/kefu'
    | '/mingshu/yunge'
    | '/mingshu'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mingshu'
    | '/register'
    | '/mingshu/baoge'
    | '/mingshu/bazi'
    | '/mingshu/kefu'
    | '/mingshu/yunge'
    | '/mingshu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MingshuRoute: typeof MingshuRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mingshu': {
      id: '/mingshu'
      path: '/mingshu'
      fullPath: '/mingshu'
      preLoaderRoute: typeof MingshuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mingshu/': {
      id: '/mingshu/'
      path: '/'
      fullPath: '/mingshu/'
      preLoaderRoute: typeof MingshuIndexRouteImport
      parentRoute: typeof MingshuRoute
    }
    '/mingshu/yunge': {
      id: '/mingshu/yunge'
      path: '/yunge'
      fullPath: '/mingshu/yunge'
      preLoaderRoute: typeof MingshuYungeRouteImport
      parentRoute: typeof MingshuRoute
    }
    '/mingshu/kefu': {
      id: '/mingshu/kefu'
      path: '/kefu'
      fullPath: '/mingshu/kefu'
      preLoaderRoute: typeof MingshuKefuRouteImport
      parentRoute: typeof MingshuRoute
    }
    '/mingshu/bazi': {
      id: '/mingshu/bazi'
      path: '/bazi'
      fullPath: '/mingshu/bazi'
      preLoaderRoute: typeof MingshuBaziRouteImport
      parentRoute: typeof MingshuRoute
    }
    '/mingshu/baoge': {
      id: '/mingshu/baoge'
      path: '/baoge'
      fullPath: '/mingshu/baoge'
      preLoaderRoute: typeof MingshuBaogeRouteImport
      parentRoute: typeof MingshuRoute
    }
  }
}

interface MingshuRouteChildren {
  MingshuBaogeRoute: typeof MingshuBaogeRoute
  MingshuBaziRoute: typeof MingshuBaziRoute
  MingshuKefuRoute: typeof MingshuKefuRoute
  MingshuYungeRoute: typeof MingshuYungeRoute
  MingshuIndexRoute: typeof MingshuIndexRoute
}

const MingshuRouteChildren: MingshuRouteChildren = {
  MingshuBaogeRoute: MingshuBaogeRoute,
  MingshuBaziRoute: MingshuBaziRoute,
  MingshuKefuRoute: MingshuKefuRoute,
  MingshuYungeRoute: MingshuYungeRoute,
  MingshuIndexRoute: MingshuIndexRoute,
}

const MingshuRouteWithChildren =
  MingshuRoute._addFileChildren(MingshuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MingshuRoute: MingshuRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
